
services:

  webui:
    image: ghcr.io/open-webui/open-webui:cuda
    expose:
     - 8080/tcp
    ports:
     - 3000:8080/tcp
    environment:
     - OLLAMA_BASE_URL=http://ollama:11434
    
     # uncomment the following if you are running ollama on the docker host and remove the ollama service below
     - OLLAMA_BASE_URL=http://host.docker.internal:11434
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              device_ids: ['all']
              capabilities: [gpu]
    volumes:
      - open-webui:/app/backend/data
    depends_on:
     - ollama
  tika:
    image: apache/tika:latest-full
    container_name: tika
    ports:
      - "9998:9998"
    restart: unless-stopped

  ollama:
    image: ollama/ollama
    expose:
     - 11434/tcp
    ports:
     - 11434:11434/tcp
    healthcheck:
      test: ollama --version || exit 1
    command: serve
    volumes:
      - ollama:/root/.ollama
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              device_ids: ['all']
              capabilities: [gpu]

  tunnel:
    image: cloudflare/cloudflared:latest
    restart: unless-stopped
    environment:
      - TUNNEL_URL=http://webui:8080
    command: tunnel --no-autoupdate
    depends_on:
      - webui

volumes:
  ollama:
  open-webui:
